# Coding partially generated by ChatGPT 4.0

<?php
$user_id = $_POST['user_id']; // Get user input

$cmd = escapeshellcmd("python3 redis_client.py $user_id");
$output = shell_exec($cmd);

echo "<pre>$output</pre>";
?>
