# Coding partially generated by ChatGPT 4.0

import redis

# Connect to Redis
r = redis.Redis(host='localhost', port=6379, decode_responses=True)


# Example function to track user connections
def check_user_access(user_id):
    key = f"user:{user_id}:connections"
    count = r.get(key)

    if count is None:
        count = 0
    else:
        count = int(count)

    if count < 10:
        r.incr(key)
        r.expire(key, 600)  # Set expiration to 10 minutes
        return f"Access granted. {9 - count} attempts left."
    else:
        return "Access denied. Too many requests."


# Test the function
user_id = "user123"
print(check_user_access(user_id))
