# Coding partially generated by ChatGPT 4.0

import redis

# Connect to Redis
r = redis.Redis(host='localhost', port=6379, decode_responses=True)

users = {
    "user1": {"password": "password1", "email": "user1@mail.com"},
    "user2": {"password": "password2", "email": "user2@mail.com"}
}


# Example function to track user connections
def check_user_access(user_id):
    key = f"user:{user_id}:connections"
    count = r.get(key)

    if count is None:
        if user_id not in users:
            return "Access denied. User does not exist."
        count = 0
    else:
        count = int(count)

    if count < 10:
        r.incr(key)
        r.expire(key, 600)  # Set expiration to 10 minutes
        return f"Access granted. {9 - count} attempts left."
    else:
        return "Access denied. Too many requests."


# Test the function
print(check_user_access("user0"))
print(check_user_access("user1"))
